### ISSUE TITLE
../out/model260k.bin -z ..\out\tok512.bin 

### ISSUE THREAD

**Issue by twobob** [icppWorld/icpp_llm#2]
do it. ;)

Not really an issue but CMON. begging for it.

**Comment by icppWorld** [comment]
@twobob ,

I implemented it, and described [here](https://github.com/icppWorld/icpp-llm/blob/main/icpp_llama2/README.md#stories260k) in the icpp_llama2/README how you can deploy `stories260K.bin` with the `tok512.bin` tokenizer.

Let me know how it works for you.
